sudo: false
language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

jobs:
  include:
    - stage: lint
      rvm: 2.6
      before_script: []
      script:
        - bundle exec rake lint

bundler_args: --without development
before_script:
  - cp config/database.yml.$DB config/database.yml
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rake

#after_success:
#  - bundle exec codeclimate-test-reporter

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e

notifications:
  webhooks:
    urls:
      - http://publify_hook.ookook.fr/travisci
    on_success: always
    on_failure: never
    on_start: never
